### ISSUE TITLE
Missing Hungarian translation.

### ISSUE THREAD

**Issue by SziaTomi** [iakmds/librecamera#104]
Missing Hungarian translation?
Why not included in the new edition the Hungarian translation was completed 5 months ago?
![camera](https://github.com/iakmds/librecamera/assets/107822077/2ade68d9-d130-4b58-8245-2734ac8c4399)
![Screenshot_2024-06-23-15-11-28-409_com iakmds librecamera](https://github.com/iakmds/librecamera/assets/107822077/814d08a4-ddfd-4f72-a572-8efe970e1fe5)

**Comment by iakmds** [comment]
Hi there,
sorry for the delay! You are right, the Hungarian translations are finished and will be included in the next version. However, I can't tell you when the next version comes out, as I'm waiting for the internal camera package to receive certain updates that I am looking forward to.
