### ISSUE TITLE
Russian and Japanese locales

### ISSUE THREAD

**Issue by mt-vkorotnev** [iakmds/librecamera#16]
I'd like to translate the app into Russian and Japanese, where do I start with?

Thanks!

**Comment by iakmds** [comment]
Hi there, 

Russian and Japanese has been added – you can translate [this russian file](https://github.com/iakmds/librecamera/blob/master/assets/l10n/app_ru.arb) and [this japanese file](https://github.com/iakmds/librecamera/blob/master/assets/l10n/app_ja.arb).

Also, if it makes sense for the languages, feel free to translate the localized app names: [This russian app name](https://github.com/iakmds/librecamera/blob/master/android/app/src/main/res/values-ru/styles.xml) and [this japanese app name](https://github.com/iakmds/librecamera/blob/master/android/app/src/main/res/values-ja/styles.xml).

Thank you!

**Comment by vladkorotnev** [comment]
Oops, I accidentally forgot to switch from work account when filing the issue!

Anyway, it's here: #17 

I don't think translating app names makes much sense in the context to be honest, to avoid confusion with the OS default camera app.
