### ISSUE TITLE
leave bottom back / menu buttons up or have an option for it

### ISSUE THREAD

**Issue by G2G2G2G** [iakmds/librecamera#20]
The bottom of some android phones have software (on screen) back / menu / home buttons or whatever they are. This app overrides those and you can't get out without pulling up the menu and sometimes it won't pull up.
I have this in my main android settings to "always show" but it doesn't on libre camera. Please at least have an option to always show in your settings if not hard coded

Thanks!

**Comment by iakmds** [comment]
Thanks for the idea, I will add a new field inside the settings, probably under the "More" section. I already received a comment about not seeing the navigation bar, so this should be a good addition. Thank you

**Comment by iakmds** [comment]
Oops, I didn't know the issue would get closed if I mention it in a PR. Before I'll close it, I'd like to get confirmation from you once the new version comes out

**Comment by G2G2G2G** [comment]
@iakmds lmao yea gitea has this just discovered it a few days ago coincidentally, with the keyword "close / closes #IssueNumber" 
I guess github has it for "fix #IssueNumber"  (probably close/closes too)

**Comment by iakmds** [comment]
Hey @G2G2G2G, the option is now present in version 1.3.0, may I close this issue? Thank you

**Comment by G2G2G2G** [comment]
awesome. works well, thanks
