### ISSUE TITLE
Can't choose storage path

### ISSUE THREAD

**Issue by hamid255** [iakmds/librecamera#22]
My phone doesn't let me choose a storage path at the start of the app. When pressing the choose path button there's just a page with no directory on it:

![choose-path](https://user-images.githubusercontent.com/35726890/196535463-92f2aaa5-7b97-491d-84c4-bdb021dd5d46.png)
![no-items](https://user-images.githubusercontent.com/35726890/196535539-34607833-2cea-4f70-b8cd-7e0f4c70d298.png)

my android's version: 5.1
app's version: 1.1.0, also existed on earlier version 1.0.0
downloaded from f-droid

**Comment by iakmds** [comment]
Hi, thank you for the issue.

That's weird, what happens though, if you press the hamburger menu at the top left? It says "Recent" in the top left, maybe there aren't recent folders and you have to select the phones storage path and go from there. Let me know if that works

**Comment by hamid255** [comment]
the hamburger menu is opened at first, and only option shown is "recent" which is empty.
![c802f965-df59-4462-85bd-175f5a74505c](https://user-images.githubusercontent.com/35726890/196659039-9be23ae6-e7a8-4a2d-99fc-411536172ace.png)

**Comment by Loughty** [comment]
Sounds like you don't have storage permissions, do you check de "allow" option when Android ask it?

![Screenshot_20221021-053321.png](https://user-images.githubusercontent.com/52808915/197164427-eea2794e-2003-4bf6-80ae-df3046283950.png)

If not, or simply don't show anything, then go to "Apps" on Settings, select LibreCamera and manually give him storage permissions!

![Screenshot_20221021-053351.png](https://user-images.githubusercontent.com/52808915/197164735-da8df169-3d2e-4829-85bf-8698179e8b8d.png)

Try and see if that solve it :D

**Comment by hamid255** [comment]
In Android 5.1 apps don't ask for permission, they either have it or not, and Libre Camera in my phone has it:

![Screenshot_2022-10-22](https://user-images.githubusercontent.com/35726890/197308347-2f94d210-b0cb-4235-b1aa-68190ada6e0b.png)

I think on/off switches for permissions were added in settings in Android 6. I don't have that.

**Comment by greyspottedfrog** [comment]
Hi, i found a bit the same problem.
App version 1.1.0 and now 1.2.0 
On Android 11:
I can choose the path internal/DCIM which works and i can choose internal/newphotos as well but here it does not work. The app can not save the pic. Btw, also the folder DCIM had to exist, the app didn't create it.
Hope this helps, froggy.

**Comment by greyspottedfrog** [comment]
Still the same in 1.3.0
and also the shutter sound does not work :-(

**Comment by iakmds** [comment]
Hey,

I'm sorry for that. I don't know where the storage issue may be coming from, I have tested the app on Android 10, 11 and 12 and it was working there... Could you explain your exact issue again, I don't think I fully understand the last part `"I can choose the path internal/DCIM which works and i can choose internal/newphotos as well but here it does not work"`, what do you mean with "here"?

Regarding the shutter sound, that's also unfortunate, if someone else has this issue too I can create a new issue for that.

Thank you.

**Comment by greyspottedfrog** [comment]
Hi,
With here i meant:
When i used the camera with storagepath internal/newphotos the app does not write the image.
Further there's no notable difference at all between the storagepath internal/DCIM and the path internsl/newphotos. The only difference is that there is no save.
Hope this explains, froggy

**Comment by gadzhi-m** [comment]
Hi. I have a similar problem. On the second step I can't specify the path, I don't get any more windows.
Xiaomi rn5, firmware RR, android 10, Libre Camera 1.3.0

**Comment by iakmds** [comment]
To @hamid255 and @gadzhi-m:
Would you like to try out an apk that includes a button sets the path `storage/emulated/0/DCIM` as the save path? If that works, it would be an issue with the file picker and I could include such button/text field to type in the path in the next version

**Comment by hamid255** [comment]
Sure, I would.

**Comment by iakmds** [comment]
Thank you. Let me know if it works, here it is:
[app-release.zip](https://github.com/iakmds/librecamera/files/9943667/app-release.zip)

**Comment by hamid255** [comment]
It does work. Thanks!

**Comment by iakmds** [comment]
Great. Thanks for your reply and your patience. I will probably add a text field for the next version (with the DCIM path as a placeholder) so others with this problem can still set a custom path

**Comment by iakmds** [comment]
Hi again. A new release is out: v1.4.0, which includes a text field to set the path. I will close this issue, in case there is anything else, please let me know :tada:
