### ISSUE TITLE
Add timer functionality

### ISSUE THREAD

**Issue by jld3103** [iakmds/librecamera#24]
Useful for taking group pictures and other stuff.

**Comment by iakmds** [comment]
Hey,

thank you – already noted in the Roadmap 👍

**Comment by jld3103** [comment]
I couldn't find it on the roadmap

**Comment by iakmds** [comment]
No problem, it is the second one: `Feature: Add photo capture delay option`, but yes, I should've named it delay/timer.

**Comment by iakmds** [comment]
Hi again, this feature is now present in 1.3.0, may I close this issue? Thanks

**Comment by jld3103** [comment]
Sure!
