### ISSUE TITLE
Feature: Change Resolution on Camera Display

### ISSUE THREAD

**Issue by lu-ckystars** [iakmds/librecamera#33]
This app would be perfect if you could change the resolution on the fly from the camera screen. Opencamera also has an option to choose between x264 and x265 when taking video, which is nice.

**Comment by iakmds** [comment]
Hi, I have added a resolution button in the new version 1.4.0 :tada:

Regarding the video options, I haven't found a way to implement it in the Flutter camera – sorry for that. Maybe it will be possible in the future. 

Anyway, I will close this issue now, in case there is anything else, let me know!
