### ISSUE TITLE
Bug: stock camera takes much higher resolution photos

### ISSUE THREAD

**Issue by zombiehoffa** [iakmds/librecamera#39]
On my poco f3 the default camera app takes 3000x4000 resolution images but this app is taking 1920x3413 resolution images thaf slso happen to be a bit blurry. I cant figure out if the bug is choosing a weird resolution for the max resolution option or this app choosing the wrong camera (there are two on the back) to take photos with. I dont sre a way to manually choose the right camera on the back in the app.

**Comment by iakmds** [comment]
Hi, thank you for the issue.

Unfortunately, you are right; the resolutions available in the Flutter camera this app is using are quite limited for now. Others have also created an issue here (#21 and #18). I will close this issue as a duplicate, though thanks again and know that this request is one of the important features that are to be implemented once it's possible.
