### ISSUE TITLE
App requires network permission?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [iakmds/librecamera#4]
Fdroid detects this app requiring network -permission. Why is that?

If not needed, it would be great if unnecessary permissions could be removed.

![Screenshot_20221005-073734_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/193989116-e2151e06-3877-4ade-82bc-8b1a2a167787.jpg)

**Comment by Glitchy-Tozier** [comment]
If none of your packages require networking-permissions (which at first glance I don't think they do), this may be due to one of the the following:
1. You accidentally released the debug-build of your app
2. You might need to manually remove the requested internet-access from some xml-file in your android-directory

**Comment by Glitchy-Tozier** [comment]
You're right, you seem to use the exact same files as I do in my app (that doesn't require internet access).
- https://github.com/iakmds/librecamera/search?q=internet
- https://github.com/Glitchy-Tozier/githo/search?q=internet


Also you seem to be using the same build commands I do:
- https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11804/diffs
- https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10627/diffs

No idea what is going on.

**Comment by iakmds** [comment]
Interesting. Let's see if it will be there in the next release too. 

I wonder if it has anything to do with the packages I am using. Do you know whether packages in Flutter can effect permission use?

**Comment by iakmds** [comment]
Well, that may at least be a hint, thank you.

**Comment by Loughty** [comment]
Ey, @iakmds, I read the thread and for curiosity I made a quick search using the words "network" and "internet", and with the last one foud this in the source:

![Screenshot 2022-10-11 at 05-23-15 Search · internet · iakmds_librecamera](https://user-images.githubusercontent.com/52808915/195052141-e2da60e6-84f3-4be4-88fc-117ff424669f.png)

https://github.com/iakmds/librecamera/blob/2de3b697072c5e0ca44d76a49e9918a8e6d3cf96/android/app/src/profile/AndroidManifest.xml

https://github.com/iakmds/librecamera/blob/2de3b697072c5e0ca44d76a49e9918a8e6d3cf96/android/app/src/debug/AndroidManifest.xml

I hope this could be usefull :smile:

**Comment by iakmds** [comment]
Hi,

thanks for the idea; Sadly the `AndroidManifest.xml` in these folders (profile and debug) are not merged with the final apk (it's a Flutter thing), therefore it cannot be the problem. What is interesting is that F-Droid marks the permission as `view network connections` which isn't even real "internet access", let's see and wait if it's still the same in the new version once it comes to F-Droid

**Comment by Loughty** [comment]
:thinking:

Well, for now, I gonna leave this links from the F-Droid:
This is the source that F-Droid uses, maybe comparing both sources (from F-Droid and Github) could give to you some hint, I think there's programs that make the comparision more easy:
https://f-droid.org/repo/com.iakmds.librecamera_1_src.tar.gz
And this is the log of the compiling process:
https://f-droid.org/repo/com.iakmds.librecamera_1.log.gz

Also, I extracted the AndroidManifiest directly from the APK of the F-Droid version, and yeah, there's nothing about network or internet:
[AndroidManifest.txt](https://github.com/iakmds/librecamera/files/9754377/AndroidManifest.txt)
Maybe you could see something that I don't.

**Comment by iakmds** [comment]
In the `AndroidManifest.xml` you extracted, it actually does say the following on line 13:

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>`

So it is the thing F-Droid detected, we need to find out where it comes from (especially if it's still there in the next F-Droid version)

**Comment by iakmds** [comment]
### Good news everyone 🎉
The next version won't require the permission for Network Access 🥳🎉

<details>
<summary><strong>For the ones interested</strong>, here is how I fixed it:</summary>
The cause for the Network Access permission request was the package <code>video_player</code> (to my surprise), which I used for displaying the video preview/thumbnail. I discovered this by creating a new blank project and adding all the packages from Libre Camera. I then removed the packages in different combinations, built the apk and inspected it's AndroidManifest for the permission. And after a couple of tries, the <code>video_player</code> package was left.

Now, the app will be using the <code>video_thumbnail</code> package instead – no need for any permissions 🎉
</details>

**Comment by Glitchy-Tozier** [comment]
Great to hear, good job! 🎉

**Comment by iakmds** [comment]
Version 1.3.1 is now on F-Droid, and as you can see, the permission is gone!
![permission](https://user-images.githubusercontent.com/111225446/199439943-fbce3e2c-3a79-43f9-aa96-b7c16481b011.png)

Can we close this issue? :tada:

**Comment by Glitchy-Tozier** [comment]
Sure :)
