### ISSUE TITLE
Distortion with devices with cutout

### ISSUE THREAD

**Issue by RestlessDevil** [iakmds/librecamera#40]
![Screenshot_20221120-112251_Libre_Camera](https://user-images.githubusercontent.com/76730510/202897042-0e2aa76a-766e-44d7-989f-cc03d83a5898.png)

My phone is Xiaomi with display cutout and I have switched navigation bar to always present. The bottom portion is great, but the cutout is causing a problem (screenshot).
I would like to suggest limiting the app to the area under the cutout, so that both can coexist, or hiding the upper portion of the navigation bar alltogether.
Great app anyway, I have switched to it from OpenCamera.

**Comment by iakmds** [comment]
Hi, thank you a lot for this issue. 

On my phone it got close to covering the top controls, yet I didn't notice it. This will be fixed in the next release. I'm glad you like the app!

**Comment by iakmds** [comment]
Hello again, the app is now limited to the safe area of the screen in the new version 1.5.0 :tada:

I will close this issue now, in case there is anything else, do let me know.
