### ISSUE TITLE
LibreCamera doesn't propose device highest resolution

### ISSUE THREAD

**Issue by iiitomo** [iakmds/librecamera#41]
LibreCamera 1.4.0 max resolution takes 3413x1920 pictures. 
While OpenCamera and Lineage Snap both take 4000x3000.
On Redmi Note7.

**Comment by iakmds** [comment]
Hi, thanks for the issue.

You are right; the resolutions available in the Flutter camera this app is using are quite limited for now. Others have also created an issue in #39, #21 and #18. I will close this issue as a duplicate, though thanks again and know that this request is one of the important features that are to be implemented once it's possible.
