### ISSUE TITLE
[Feature Request] Default Camera App

### ISSUE THREAD

**Issue by SkyDvl** [iakmds/librecamera#44]
I would like to suggest adding the ability to make Libre Camera the default camera app for Android, so that it's possible to access it easily from the lock screen. Thank you in advance

**Comment by iakmds** [comment]
Hi there, thanks for the issue.

Though I'd love to implement such option, unfortunately there is no way for me as the developer to set the app as the default camera app. There are some solutions you can try as a user though:

1. **Set default camera app in settings**. Note that only some Android versions support this options (Settings → Apps → Default apps → Camera → Libre Camera)
2. **Disable the default camera app** so only Libre Camera is available (Settings → Apps → Camera → Disable). Note that not every phone allows you to do that. In case you _really_ want to remove the default camera **and you know what you're doing**, you can use ADB to uninstall it (but please do your research about the potential implications!)
3. Try out **third-party solutions** such as [Default App Manager (Play Store)](https://play.google.com/store/apps/details?id=com.tintage.android.defaultappmanager) or [Better Open With (Play Store)](https://play.google.com/store/apps/details?id=com.aboutmycode.betteropenwith)

These are the options I found while researching, I hope I could help. Let me know if there is anything else, I will close the issue for now. Thanks again!
