### ISSUE TITLE
Support encoding natively to JPEG XL format

### ISSUE THREAD

**Issue by nekohayo** [iakmds/librecamera#45]
Why: [JPEG XL](https://jpeg.org/jpegxl/) is the future of all image formats. It is a new royalty-free image codec targeting the image quality as found on the web, providing about 60% size savings when compared to original JPEG at the same perceptual quality (in my experience, it's been more like 80%), while supporting modern features like HDR, animation, alpha channel, lossless and backwards-compatible JPEG recompression (in my experience, you can save an average of roughly 20% in filesizes just by doing that), lossless and progressive modes. It is based on Google's PIK and Cloudinary's FUIF, and is an ISO standard.

It can even losslessly recompress existing JPEG images.

Explanation here:

* https://jpegxl.info/why-jxl.html
* https://www.slideshare.net/cloudinarymarketing/imagecon-2019-jon-sneyer

Reference implementation here: https://github.com/libjxl/libjxl/

Software implementations, and industry adoption:
* Many pieces of software support JPEG XL (see [the list on Wikipedia](https://en.wikipedia.org/wiki/JPEG_XL#Official_support))
* Many big industry players have [voiced their support](https://en.wikipedia.org/wiki/JPEG_XL#Industry_support_and_adoption) for JPEG XL

The easiest way to implement this would be to integrate [libjxl](https://github.com/libjxl/libjxl), which is already well-optimized for ARM.

**Comment by iakmds** [comment]
Good evening, thank you. It does indeed sound really interesting. Unfortunately I am quite limited by the Flutter camera, which is why this would take a lot of effort to implement.

In fact, a request for JPEG XL, along other formats, was already proposed in another issue, see #13. Because I'll leave the other issue open I'm going to close this one as a duplicate.
