### ISSUE TITLE
Doesn't add photos to mediastore

### ISSUE THREAD

**Issue by maemunman** [iakmds/librecamera#5]
When a new photo is taken, it should be added to android's mediastore so that it shows up in the gallery app.

It doesn't currently. I have to restart my phone to see the new photos in the gallery

**Comment by iakmds** [comment]
Hi there, 

Version 1.1.0 has been released, which should fix the issues – get it from the [releases](https://github.com/iakmds/librecamera/releases) page and please let me know if everything now works!

**Comment by iakmds** [comment]
I will close this issue now as it should now work. Feel free to open a new issue in case there is anything else!

**Comment by maemunman** [comment]
indeed it works now. I received the update from fdroid yesterday

**Comment by iakmds** [comment]
Great to hear, thank you!
