### ISSUE TITLE
[Question] Would a streaming feature (eg to OBS) be possible?

### ISSUE THREAD

**Issue by SmutnyStefan** [iakmds/librecamera#59]
Every single app that does this is closed source and paid or is severely limited

**Comment by iakmds** [comment]
Hey there,
thanks for the question. Interesting feature, but I think it is out of the scope of Libre Camera... I try to put the focus on making it a nice camera app.
Too bad that there isn't any viable option out there at the moment, let me know if you find one though!

(Will close this issue, but feel free to comment more)

**Comment by HIHIQY1** [comment]
Hey, I had the same problem! What you could do as a workaround is use [scrcpy](https://github.com/Genymobile/scrcpy) if you're on Android, then add an OBS window capture which captures the scrcpy window :)

**Comment by Ernest1338** [comment]
@SmutnyStefan Have you tried using https://vdo.ninja/?
