### ISSUE TITLE
[Question] Camera resolution preset 

### ISSUE THREAD

**Issue by GrozaTE** [iakmds/librecamera#61]
Resolution preset limited to 16:9 aspect ratio but camera sensor capable 4:3.
This app even cutoff what it showed in viewport 
Is it possible to capture whole 4:3 or maybe view in viewport with grid(16:9 frame) 
so it be predictable what end picture would look like

**Comment by iakmds** [comment]
Hi there,
you are right, unfortunately it is currently not possible to choose custom resolutions apart from the presets, at least for now. I would implement them as soon as it would become possible.

Here are 3 issues regarding this problem:
- In Libre Camera: #21
- In Flutter: https://github.com/flutter/flutter/issues/45665
- In Flutter's CameraX rewrite, where I also commented: https://github.com/flutter/flutter/issues/120462

I will close this issue as a duplicate (#21). Feel free to comment or ask anything else though!
