### ISSUE TITLE
[Feature request] Use Material You with dynamic colors

### ISSUE THREAD

**Issue by meenbeese** [iakmds/librecamera#68]
**Describe the solution you'd like**
Even though Material You has been partially implemented as mentioned in #60, proper implementation is not here. What I mean by this is that the application does not change its colors and overall theme based on the color of the wallpaper. Blue is the default and only color available currently, which is not enough given that Material You is all about customization and personalization.

**Additional context**
There are other great apps which implement proper Material You and are written in Dart. The first that comes to my mind is [Obtainium](https://github.com/ImranR98/Obtainium), which you can check its source code to help with the implementation in your own app.

**Comment by iakmds** [comment]
Hey @meenbeese,
thanks for the issue! Also thank you for linking the example. I took a look at it will implement it in the next version :+1:

**Comment by meenbeese** [comment]
Thank you for addressing the issue so fast. I can't wait for the next release to test it!

**Comment by iakmds** [comment]
Hey @meenbeese again,
This issue should now be resolved with the release [v1.9.0](https://github.com/iakmds/librecamera/releases/tag/v1.9.0)!
It's available on [F-Droid](https://f-droid.org/packages/com.iakmds.librecamera/) as well now. Let me know if it's working as expected.

**Comment by meenbeese** [comment]
Hello @iakmds! I tried the new version 1.9.0 and it works perfectly. I like how the custom color is subtle and not aggressive. I also appreciate the AMOLED black theme as it looks great with the Material You colors. Thanks for implementing this.

**Comment by iakmds** [comment]
I'm really happy to hear that! 
I assume we can close this issue now :smiley:
