### ISSUE TITLE
[Feature request] Voulme buttons to capture photo

### ISSUE THREAD

**Issue by rakibdev** [iakmds/librecamera#69]
To use only one hand when taking selfie.

**Comment by iakmds** [comment]
Thank you, this is on the roadmap as well. It should be implemented in the next versions.

**Comment by iakmds** [comment]
This issue should now be resolved with the release [v1.8.0](https://github.com/iakmds/librecamera/releases/tag/v1.8.0)!
It should come out on [F-Droid](https://f-droid.org/packages/com.iakmds.librecamera/) soon as well. Let me know when I can close the issue.

**Comment by rakibdev** [comment]
@iakmds thanks, working. can be closed.
