### ISSUE TITLE
Suggest about formats

### ISSUE THREAD

**Issue by joe2047** [iakmds/librecamera#71]
Hello 

I want this project can support HDR and can save file AVIF format photo from the future .

Secondly make the video recorder set the bitrate size and  hope can save more videos file formats for example .webm , .av1

Thanks

**Comment by iakmds** [comment]
Hey there, thanks for the issue.

There are already separate issues for your suggestions:
- HDR support: #31 
- AVIF, .webm, .av1: #13
- Bitrate size: #21 

I will close this issue as a duplicate. :+1:
