### ISSUE TITLE
Gallery Issue

### ISSUE THREAD

**Issue by DarkArrow9** [iakmds/librecamera#8]
Hey there, I cannot see any clicked photos in my gallery or in any instant app. I have to upload this pics as files to send someone. Hope you will fix it.

**Comment by iakmds** [comment]
Hi,

thanks for the issue, I am already aware of it and will fix it soon!

**Comment by iakmds** [comment]
Version 1.1.0 has been released, which should fix the issues – get it from the [releases](https://github.com/iakmds/librecamera/releases) page and please let me know if everything now works!

**Comment by iakmds** [comment]
I will close this issue now as it should now work. Feel free to open a new issue in case there is anything else!
