### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by Loughty** [iakmds/librecamera#9]
I'm already working on it :smile:

![capture](https://user-images.githubusercontent.com/52808915/194678713-50325552-c488-4fc7-b5dc-a6c62bac9a74.png)

**Comment by iakmds** [comment]
Hola,

¡muchas gracias! I have created the necessary files – you simply have to translate [this](https://github.com/iakmds/librecamera/blob/master/assets/l10n/app_es.arb) file, just like you did in your screenshot. I know some Spanish, so I'll be able to "check" the translations as well ;)
